### ISSUE TITLE
How fast is training, and de-identifying a large corpus?

### ISSUE THREAD

**Issue by ssoheilmn** [maxfriedrich/deid-training-data#1]
I have two questions regarding speed:
1. Do we "have to" train the data, or can we use a pretrained model already trained by you? How fast is it to train the algorithm on our own data? Let's say if we have 10 GB of text.
2. After training is done, how fast is it to de-identify text? Let's say if we have 10GB of text, or if we want to de-identify documents on the fly, how many milliseconds does it take to de-identify a document of 500 words, assuming we already loaded the model in memory and kept it that way.

Thanks.

**Comment by maxfriedrich** [comment]
Hey @ssoheilmn, thanks for you interest in my work. Sorry for the late reply!

1. I don't provide a trained model at this point. I only trained it on the i2b2 corpus, which is around 10 MB of text -- training took over night on a laptop to stabilize.
2. De-identification is around 500ms for 500 words on my laptop. (Keep in mind that this is non-optimized research code)

Hope this helped a bit!
