### ISSUE TITLE
TypeError: type object got multiple values for keyword argument 'digit_strategy

### ISSUE THREAD

**Issue by dadelani** [maxfriedrich/deid-training-data#2]
Thank you for uploading the code for your ACL paper. I was going through the instructions on the read me file. Everything seems to work well except that running the code throws this error:

python -m deid.experiment deid_resources/config/generated/config_001.yaml

TypeError: type object got multiple values for keyword argument 'digit_strategy

I tried it with both Glove Embeddings and FastText with the same error,. Can you please help to look into the error or give explanation on how to resolve it? Thank you

**Comment by maxfriedrich** [comment]
Hei David, sorry about this! The `digit_strategy` argument as well as `include_original` were at the wrong place in the config template. Let me know if it works now!

**Comment by maxfriedrich** [comment]
Feel free to re-open this or make a new issue if you run into any more problems! 👍

**Comment by dadelani** [comment]
Thank you very much for your reply. The new config files you updated worked well. However, there are still some bugs in the code. I will open it on the new issue
